name: optimizely_flutter_sdk
description: This repository houses the Flutter SDK for use with Optimizely Feature Experimentation, Optimizely Full Stack (legacy), and Optimizely Rollouts.
version: 1.0.2-beta
homepage: https://github.com/optimizely/optimizely-flutter-sdk

environment:
  sdk: '>=2.16.2 <=3.1.2'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  collection: ^1.16.0

flutter:
  plugin:
    platforms:
      android:
        package: com.optimizely.optimizely_flutter_sdk
        pluginClass: OptimizelyFlutterSdkPlugin
      ios:
        pluginClass: OptimizelyFlutterSdkPlugin
      macos:
        pluginClass: OptimizelyFlutterSdkPlugin
      windows:
        pluginClass: OptimizelyFlutterSdkPluginCApi
